const actionTypes = {
    ADMIN: 'ADMIN',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    GET_CURRENT_USER: 'GET_CURRENT_USER',

    LOADING: 'LOADING',
    ALERT: 'ALERT',

    GET_LOCATION: 'GET_LOCATION',
    REMOVE_LOCATION: 'REMOVE_LOCATION',

    WISHLIST: 'WISHLIST',
    ADD_WISHLIST: 'ADD_WISHLIST',
    SHOW_WISHLIST: 'SHOW_WISHLIST',
    RESET_WISHLIST: 'RESET_WISHLIST',
    REMOVE_WISHLIST: 'REMOVE_WISHLIST',
}

export default actionTypes;